apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: judge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: judge
    spec:
      containers:
      - name: judge
        image: darkofabijan/judge:v3
        ports:
        - containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: judge
spec:
  selector:
    app: judge
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
      nodePort: 30002
  type: LoadBalancer
