# Generated by `mix grpc.gen`.
# DO NOT EDIT!

defmodule Addy.Adder.Service do
  use GRPC.Service, name: "addy.Adder"

  rpc :Add, Addy.NumbersToAdd, Addy.Sum
end

defmodule Addy.Adder.Stub do
  use GRPC.Stub, service: Addy.Adder.Service
end

defmodule Addy do
  use Protobuf, """
syntax = "proto3";

package addy;

service Adder {
  rpc Add (NumbersToAdd) returns (Sum) {}
}

message NumbersToAdd {
  int32 a = 1;
  int32 b = 2;
}

message Sum {
  int32 result = 1;
}
  """
end
