apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spitter
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: spitter
    spec:
      containers:
      - name: spitter
        image: darkofabijan/spitter:latest
        ports:
        - containerPort: 4567
        env:
          - name: test_env_var
            value: "hello from k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: spitter
spec:
  selector:
    app: spitter
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
      nodePort: 30001
  type: LoadBalancer
