apiVersion: v1
kind: Service
metadata:
  name: spitter
spec:
  selector:
    app: spitter
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
      nodePort: 30001
  type: LoadBalancer
