# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addy.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "addy.NumbersToAdd" do
    optional :a, :int32, 1
    optional :b, :int32, 2
  end
  add_message "addy.Sum" do
    optional :result, :int32, 1
  end
end

module Addy
  NumbersToAdd = Google::Protobuf::DescriptorPool.generated_pool.lookup("addy.NumbersToAdd").msgclass
  Sum = Google::Protobuf::DescriptorPool.generated_pool.lookup("addy.Sum").msgclass
end
