# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: addy.proto for package 'addy'

require 'grpc'
require_relative 'addy_pb'

module Addy
  module Adder
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'addy.Adder'

      rpc :Add, NumbersToAdd, Sum
    end

    Stub = Service.rpc_stub_class
  end
end
