apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ventilator
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: ventilator
        version: v2
    spec:
      containers:
      - name: ventilator
        image: darkofabijan/ventilator:v3
        ports:
        - containerPort: 4567
